In [ ]:
import os
from os.path import exists, join, basename, splitext

git_repo_url = 'https://github.com/CMU-Perceptual-Computing-Lab/openpose.git'
project_name = splitext(basename(git_repo_url))[0]
if not exists(project_name):
  # see: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/949
  # install new CMake becaue of CUDA10
  !wget -q https://cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.tar.gz
  !tar xfz cmake-3.13.0-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local
  # clone openpose
  !git clone -q --depth 1 $git_repo_url
  !sed -i 's/execute_process(COMMAND git checkout master WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/execute_process(COMMAND git checkout f019d0dfe86f49d1140961f8c7dec22130c83154 WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/g' openpose/CMakeLists.txt
  # install system dependencies
  !apt-get -qq install -y libatlas-base-dev libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler libgflags-dev libgoogle-glog-dev liblmdb-dev opencl-headers ocl-icd-opencl-dev libviennacl-dev
  # # install python dependencies
  # !pip install -q youtube-dl
  # # build openpose
  # !cd openpose && rm -rf build || true && mkdir build && cd build && cmake .. && make -j`nproc`

Selecting previously unselected package libgflags2.2.
(Reading database ... 128208 files and directories currently installed.)
Preparing to unpack .../00-libgflags2.2_2.2.2-1build1_amd64.deb ...
Unpacking libgflags2.2 (2.2.2-1build1) ...
Selecting previously unselected package libgflags-dev.
Preparing to unpack .../01-libgflags-dev_2.2.2-1build1_amd64.deb ...
Unpacking libgflags-dev (2.2.2-1build1) ...
Selecting previously unselected package libgoogle-glog0v5.
Preparing to unpack .../02-libgoogle-glog0v5_0.4.0-1build1_amd64.deb ...
Unpacking libgoogle-glog0v5 (0.4.0-1build1) ...
Selecting previously unselected package libgoogle-glog-dev.
Preparing to unpack .../03-libgoogle-glog-dev_0.4.0-1build1_amd64.deb ...
Unpacking libgoogle-glog-dev (0.4.0-1build1) ...
Selecting previously unselected package libleveldb1d:amd64.
Preparing to unpack .../04-libleveldb1d_1.22-3ubuntu2_amd64.deb ...
Unpacking libleveldb1d:amd64 (1.22-3ubuntu2) ...
Selecting previously unselected package libleveldb-dev

In [ ]:
!cd openpose && rm -rf build || true && mkdir build && cd build && cmake .. 

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GCC detected, adding compile flags
-- GCC detected, adding compile flags
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threa

In [ ]:
!cd openpose && cd build && cmake -D BUILD_PYTHON:BOOL=ON ..

-- GCC detected, adding compile flags
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 11.8
-- Found cuDNN: ver. 8.7.0 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75 sm_80 sm_86
-- Found cuDNN: ver. 8.7.0 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
HEAD is now at 1807aada Added Ampere arch's (CUDA11)
-- Caffe will be built from source now.
-- Download the models.
-- Downloading B

In [ ]:
!cd openpose && cd build  && make -j`nproc`

Streaming output truncated to the last 5000 lines.
                 from /usr/local/cuda/include/thrust/device_vector.h:25,
                 from /content/openpose/3rdparty/caffe/src/caffe/util/math_functions.cu:2:
/usr/local/cuda/include/thrust/detail/config/cpp_dialect.h:131:13: warning: Thrust requires at least C++14. C++11 is deprecated but still supported. C++11 support will be removed in a future release. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
  131 |      THRUST_COMPILER_DEPRECATION_SOFT(C++14, C++11);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                           
In file included from /usr/local/cuda/include/cub/util_arch.cuh:36,
                 from /usr/local/cuda/include/cub/detail/device_synchronize.cuh:20,
                 from /usr/local/cuda/include/thrust/system/cuda/detail/util.h:36,
   

Edit build/CMakeCache.txt as:
1. PYBIND11_INSTALL:BOOL=ON
2. PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.8
3. PYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8m.so


In [ ]:
!cd openpose && cd build && cmake ..

-- GCC detected, adding compile flags
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 11.8
-- Found cuDNN: ver. 8.7.0 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75 sm_80 sm_86
-- Found cuDNN: ver. 8.7.0 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
HEAD is now at 1807aada Added Ampere arch's (CUDA11)
-- Caffe will be built from source now.
-- Adding Example calibration.bin
-- Add

In [ ]:
!cd openpose && cd build  && make -j`nproc`

[  3%] Built target openpose_lib
[  3%] Linking CXX shared library libopenpose.so
[ 41%] Built target openpose
[ 46%] Built target openpose_core
[ 46%] Linking CXX executable calibration.bin
[ 46%] Linking CXX executable tutorial_api_thread_1_user_processing_function.bin
[ 47%] Built target calibration.bin
[ 47%] Linking CXX executable tutorial_add_module_custom_post_processing.bin
[ 48%] Built target tutorial_api_thread_1_user_processing_function.bin
[ 49%] Linking CXX executable tutorial_api_thread_2_user_input_processing_output_and_datum.bin
[ 49%] Built target tutorial_add_module_custom_post_processing.bin
[ 49%] Linking CXX executable openpose.bin
[ 49%] Built target tutorial_api_thread_2_user_input_processing_output_and_datum.bin
[ 49%] Linking CXX executable 18_synchronous_custom_all_and_datum.bin
[ 49%] Built target 18_synchronous_custom_all_and_datum.bin
[ 50%] Built target openpose.bin
[ 51%] Linking CXX executable 17_synchronous_custom_output.bin
[ 52%] Linking CXX executabl

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


!!!! IF built target pyopenpose appears at last line then successfully built.

In [ ]:
! cd openpose && cd build && cd examples && cd tutorial_api_python && python detect.py

Starting OpenPose Python Wrapper...

Error:
Cuda check failed (100 vs. 0): no CUDA-capable device is detected

Coming from:
- /content/openpose/src/openpose/gpu/cuda.cpp:getCudaGpuNumber():48
- /content/openpose/src/openpose/gpu/cuda.cpp:cudaCheck():37
- /content/openpose/src/openpose/gpu/cuda.cpp:getCudaGpuNumber():58
- /content/openpose/src/openpose/gpu/gpu.cpp:getGpuNumber():27
- /content/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1221
- /content/openpose/include/openpose/wrapper/wrapper.hpp:start():442
- /content/openpose/python/openpose/openpose_python.cpp:start():216

Error:
Cuda check failed (100 vs. 0): no CUDA-capable device is detected

Coming from:
- /content/openpose/src/openpose/gpu/cuda.cpp:getCudaGpuNumber():48
- /content/openpose/src/openpose/gpu/cuda.cpp:cudaCheck():37
- /content/openpose/src/openpose/gpu/cuda.cpp:getCudaGpuNumber():58
- /content/openpose/src/openpose/gpu/gpu.cpp:getGpuNumber():27
- /content/openpose/include/openpos

In [ ]:
! cd openpose && cd build && cd examples && cd tutorial_api_python && python detect.py 

Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.


In [ ]:
! nvidia-smi

Sat Jan 21 15:13:17 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!cd openpose && ./build/examples/tutorial_api_cpp/detect.bin 

Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
frames :25


In [ ]:
!cd openpose && cd build && cd examples && cd tutorial_api_python && python detect.py

Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
2.02
[[[7.6265356e+02 1.9242207e+02 8.3686030e-01]
  [7.6456738e+02 2.7481546e+02 7.9287124e-01]
  [6.5287091e+02 2.7276138e+02 7.1169198e-01]
  [6.1956525e+02 4.5892303e+02 6.4237869e-01]
  [6.3134381e+02 6.3134827e+02 7.3534769e-01]
  [8.8214014e+02 2.7872003e+02 7.1097726e-01]
  [9.3503186e+02 4.4910675e+02 7.5942564e-01]
  [8.5663684e+02 4.1393646e+02 8.2181263e-01]
  [7.6069830e+02 6.1762646e+02 3.8478667e-01]
  [6.9793658e+02 6.2349408e+02 3.4212252e-01]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [8.2531464e+02 6.1567981e+02 3.1812462e-01]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [7.4496631e+02 1.6118655e+02 9.1737545e-01]
  [7.9003827e+02 1.6311136e+02 9.4131052e-01]
  [7.1558972e+02 1.6303268e+02 8.8361943e-01]
  [8.2144440e+02 1.6504199e+02 9.4604099

In [ ]:
!cd openpose && cd build && cmake .. && make -j`nproc`

-- GCC detected, adding compile flags
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 11.2
-- Found cuDNN: ver. 8.1.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_75
-- Found cuDNN: ver. 8.1.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
HEAD is now at 1807aada Added Ampere arch's (CUDA11)
-- Caffe will be built from source now.
-- Adding Example calibration.bin
-- Adding Example tutorial_add_module_custom_post_processing.bin
-- Adding Example tutorial_api_thread_1_user_processing_function.bin
-- Adding Example

In [ ]:
!zip -r /content/drive/MyDrive/openpose.zip /content/openpose

In [ ]:
!pip install youtube-dl

In [ ]:
import os 
os.chdir('/content/drive/MyDrive/openpose')

!wget -c '/content/openpose.zip' --no-check-certificate

In [ ]:
!youtube-dl -f 22 --get-url https://www.youtube.com/watch?v=mMZriSvaVP8

In [ ]:
!youtube-dl -f 22 --get-url A_Cameraman_Gets_Too_Close_To_Conan_-_CONAN_on_TBS-5M7NU23GHO4.mkv

In [ ]:
! youtube-dl "ytsearch:A_Cameraman_Gets_Too_Close_To_Conan_-_CONAN_on_TBS-5M7NU23GHO4.mkv" 

**This is for backend part of downloading youtube videos for conan**

In [ ]:
import pandas as pd
import youtube_dl as yt
import numpy as np
from subprocess import call
import os

In [ ]:
video_file = pd.read_csv("/content/videos_links.csv")
intervals_file = pd.read_csv("/content/intervals_df.csv") 

In [ ]:
conan = video_file[video_file['speaker'] == 'conan']

In [ ]:
print(conan)

In [ ]:
# changing pandas dataframe to numpy array and removing first column named speaker
links = np.array(conan.iloc[:,1:3])

In [ ]:
print(type(links[0][0]))

<class 'str'>


In [ ]:
print(links.shape[0])

326


In [ ]:
# extract intervals for specific video from intervals_csv_file
intervals_data = intervals_file[intervals_file['video_fn'] == links[0][0]]
print(intervals_data)
intervals_for_video = np.array(intervals_data.iloc[:,4:6])
print(intervals_for_video[0])

In [ ]:
print(intervals_for_video.shape)

(8, 2)


In [ ]:
# loop this till every interval of specific video is extracted
start_time = intervals_for_video[0][0]
end_time = intervals_for_video[0][1]

start_time = start_time.split()
end_time = end_time.split()

start_time = start_time[1]
end_time = end_time[1]
print(start_time)
print(end_time)

00:00:09.275943
00:00:12.946280


In [ ]:
print(links[0][1])
link = str(links[0][1])
print(type(link))
print(link)

NameError: ignored

extracted every interval of a video into intervals_for_video

In [ ]:
command = 'youtube-dl -f 22 --get-url {link}'.format(link = link)
print(command)

youtube-dl -f 22 --get-url http://www.youtube.com/watch?v=oqZM4IPiI3A


In [ ]:
!youtube-dl -f 22 --get-url 'link'

ERROR: 'link' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:link" ) to search YouTube


In [ ]:
res = call('youtube-dl -f 22 --get-url {link}'.format(link = link) ,shell= True)

print(res)

1


In [ ]:
! command

In [ ]:
### get url for specific video
!youtube-dl -f 22 --get-url http://www.youtube.com/watch?v=oqZM4IPiI3A

https://rr4---sn-5hne6ns6.googlevideo.com/videoplayback?expire=1673801404&ei=XNrDY-3MMoP01gK01qeQAw&ip=34.90.107.6&id=o-ACihTWHhAFJaHmxBjG89ifs54ZylNBFkVZA2wDrfOJuo&itag=22&source=youtube&requiressl=yes&mh=71&mm=31%2C29&mn=sn-5hne6ns6%2Csn-5hneknee&ms=au%2Crdu&mv=m&mvi=4&pl=20&vprv=1&mime=video%2Fmp4&ns=umBfaKmsktVdh3b-sdT0bu4K&cnr=14&ratebypass=yes&dur=193.747&lmt=1525975559267806&mt=1673779507&fvip=3&fexp=24007246&c=WEB&n=ehREMOesVl2t8an&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQn14pfulBWaReiHikqMEns6-DqCCqKhQ0wo2yd_nZkUCIQCblh2t6SXZLkCfcFLdOIGEf8U3t9QD9AQPGr792dUDCA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRAIgPgxWEj01mWM0HSh83iQP5beR5F-DRcGWsB9NGKJTp5MCICoP8Z4XF_4F7n2tNngYPQ8nphWOdOy_Ybhk4pyBtR5W


wrrr

In [ ]:
! ffmpeg -ss 00:00:20 -i $(youtube-dl -f 22 --get-url http://www.youtube.com/watch?v=oqZM4IPiI3A) -to 00:00:30 -c copy -copyts test8.mp4

ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-li

In [ ]:
! ffmpeg $(youtube-dl -g 'http://www.youtube.com/watch?v=oqZM4IPiI3A' | sed "s/.*/-ss 00:00:10 -i &/") -t 00:00:20 -c copy test7.mp4 ###not working

ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-li

In [ ]:
! ffmpeg -ss 00:00:20 -i video.mp4 -t 00:00:30 -c copy -copyts test6.mp4 ###video uploaded 

/bin/bash: -t: command not found
ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-lib

In [ ]:
! youtube-dl http://www.youtube.com/watch?v=oqZM4IPiI3A   ### way to download video directly using youtube-dl

[youtube] oqZM4IPiI3A: Downloading webpage
[download] Destination: Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.f137.mp4
[download] 100% of 44.85MiB in 12:19
[download] Destination: Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.f140.m4a
[download] 100% of 2.99MiB in 00:49
[ffmpeg] Merging formats into "Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.mp4"
Deleting original file Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.f137.mp4 (pass -k to keep)
Deleting original file Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.f140.m4a (pass -k to keep)


In [ ]:
! python hello.py

Conan_-_Trump_Won_t_Hold_Summit_At_DMZ_Because_The_Lines_Are_Too_Long_-_CONAN_on_TBS-oqZM4IPiI3A.mkv
00:00:09.275943   00:00:12.946280
ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame

In [ ]:
!pip install ffmpeg

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6084 sha256=5b219ad2cdc37dc55474b0e6751f75bb7e8285ceac029a942ac0060a341cc0c1
  Stored in directory: /root/.cache/pip/wheels/30/33/46/5ab7eca55b9490dddbf3441c68a29535996270ef1ce8b9b6d7
Successfully built ffmpeg


resampling part


In [ ]:
!python resample.py

29.97002997002997
ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-l

In [ ]:
!pip install youtube-dl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 32.3 MB/s eta 0:00:00


In [ ]:
!youtube-dl http://www.youtube.com/watch?v=oqZM4IPiI3A

[youtube] oqZM4IPiI3A: Downloading webpage
[download] Destination: Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.f137.mp4
[download] 100% of 44.85MiB in 09:16
[download] Destination: Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.f140.m4a
[download] 100% of 2.99MiB in 00:37
[ffmpeg] Merging formats into "Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.mp4"
Deleting original file Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.f137.mp4 (pass -k to keep)
Deleting original file Trump Won’t Hold Summit At DMZ Because The Lines Are Too Long _ CONAN on TBS-oqZM4IPiI3A.f140.m4a (pass -k to keep)


In [ ]:
!pip install idm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.8/172.8 KB 9.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 46.7 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
! python resample.py

29.97002997002997
ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-l

In [ ]:
! pip install ffmpeg

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6084 sha256=a6605279b7cf6c9b0edfa67926163c484d397d8832b779c4d3c3290d22786a9b
  Stored in directory: /root/.cache/pip/wheels/30/33/46/5ab7eca55b9490dddbf3441c68a29535996270ef1ce8b9b6d7
Successfully built ffmpeg
